import localFont from "next/font/local";
import "./globals.css";
// import { ThemeProvider } from "next-themes";
import { Slide, ToastContainer } from "react-toastify";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: {
    template: "%s | ecopower",
    default: "The infopanel for ecopower",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={"dark"}>
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >

    {/*<ThemeProvider*/}
    {/*  // theme={theme}*/}
    {/*  attribute={"class"}*/}
    {/*  defaultTheme={"system"}*/}
    {/*  enableSystem*/}
    {/*  disableTransitionOnChange*/}
    {/*>*/}
    {children}
    <ToastContainer
      position="bottom-center"
      autoClose={3000}
      limit={2}
      hideProgressBar={false}
      newestOnTop={false}
      closeOnClick
      rtl={false}
      pauseOnFocusLoss
      draggable
      pauseOnHover
      theme="colored"
      transition={Slide}
    />
    {/*</ThemeProvider>*/}
    </body>
    </html>
  );
}
